# Generated by Django 4.1.1 on 2022-11-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('review', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
